name: Compile QX
description: Install tools and compile QX
inputs:
  build_type:
    required: true
    description: Is the build a debug or release version
  shell:
    required: true
    description: Which shell to use for the `run` command

runs:
  using: composite
  steps:
    - name: Install conan
      run: python3 -m pip install --upgrade pip conan
      shell: ${{ inputs.shell }}
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Configure and build
      run: |
        conan profile detect
        build_type=${{ inputs.build_type }}
        lowercase_build_type=$(echo ${build_type} | tr '[:upper:]' '[:lower:]')
        conan build . -pr=conan/profiles/tests-${lowercase_build_type} -b missing
      shell: ${{ inputs.shell }}
    - name: Test
      working-directory: build/${{ inputs.build_type }}
      run: ctest -C ${{ inputs.build_type }} --output-on-failure
      shell: ${{ inputs.shell }}
