name: Compile QX
description: Install toosl and compile QX
inputs:
  compiler:
    required: true
    description: Which compiler to use
  build_type:
    required: true
    description: Is the build a debug or release version
  shell:
    required: true
    description: Which shell to use for the `run` command

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install conan
      run: python -m pip install --upgrade pip conan
      shell: ${{ inputs.shell }}
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Configure and build
      run: |
        conan profile detect
        build_type=${{ matrix.build_type }}
        lowercase_build_type=$(echo ${build_type} | tr '[:upper:]' '[:lower:]')
        conan build . -pr=conan/profiles/tests-${lowercase_build_type} -b missing
      shell: ${{ inputs.shell }}
    - name: Test
      working-directory: build/${{ matrix.build_type }}
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
      shell: ${{ inputs.shell }}
