


qubits 16


.entangle(10)
  h q0
  cnot q0,q1
  cnot q0,q2
  cnot q0,q3
  cnot q0,q4
  cnot q0,q5
  cnot q0,q6
  cnot q0,q7
  cnot q0,q8
  cnot q0,q9
  cnot q0,q10
  cnot q0,q11
  cnot q0,q12
  cnot q0,q13
  cnot q0,q14
  cnot q0,q15

# .measure
  measure q0
  measure q1
  measure q2
  measure q3
  measure q4
  measure q5
  measure q6
  measure q7
  measure q8
  measure q9
  measure q10
  measure q11
  measure q12
  measure q13
  measure q14
  measure q15
  display_binary
