# this makefile cleans the tempory files created during the installation
clean:
	@-echo "Cleaning temporary files created by install ..."
	@-rm -rf build cbuild qxelarator.egg-info dist qxelarator/qxelarator.py qxelarator/_qxelarator.so
	@-echo "Done"
