/* confdefs.h */
#define PACKAGE_NAME "qx-simulator"
#define PACKAGE_TARNAME "qx-simulator"
#define PACKAGE_VERSION "0.1.3"
#define PACKAGE_STRING "qx-simulator 0.1.3"
#define PACKAGE_BUGREPORT "nader.khammassi@gmail.com"
#define PACKAGE_URL ""
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBPTHREAD 1
#define HAVE_POW 1
#define HAVE_SQRT 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_MACH_MACH_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
