name: Assets

on:
  release:
    types:
      - created
  push:
    branches:
      - "release**"

jobs:
  cibw-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,  # Linux/x64
          macos-13,  # MacOS/x64
          windows-latest,  # Windows/x64
          ubuntu-24.04-arm,  # Linux/ARM64
          macos-14  # MacOS/ARM64
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish-python-packages:
    name: Publish Python packages
    needs:
      - cibw-wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        id: download
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ${{ steps.download.outputs.download-path }}/cibw-*
