name: Test

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  cpp:
    name: "C++ tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install bison flex
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
      - uses: actions/cache@v2
        if: matrix.os == 'windows-latest'
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-cpp-0
          restore-keys: |
            ${{ runner.os }}-chocolatey-cpp-
            ${{ runner.os }}-chocolatey-
      - name: Install dependencies
        if: matrix.os == 'windows-latest'
        run: choco install winflexbison3 --version 2.5.24.20210105
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=Debug -DQX_BUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DQX_CPU_COMPATIBILITY_MODE=ON
      - name: Build
        run: cmake --build . --parallel 5

      # - name: Test
      #   run: |
      #     ctest -C Debug --output-on-failure

      - name: Install gdb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y gdb
      
      - name: Install valgrind
        if: matrix.os == 'ubuntu-latest'
        run: |
          git clone https://sourceware.org/git/valgrind.git
          cd valgrind
          ./autogen.sh
          ./configure --prefix=$HOME
          make -j16
          make install
      
      - name: Test under valgrind
        if: matrix.os == 'ubuntu-latest'
        run: |
          $HOME/bin/valgrind --trace-children=yes --leak-check=yes ctest -C Debug -R "test_rand" --output-on-failure
      - name: Test under gdb
        if: matrix.os == 'ubuntu-latest'
        run: |
          gdb -ex="set confirm off" -ex "set follow-fork-mode child" -ex "set breakpoint pending on" -ex "break malloc_printerr" -ex "info break" -ex "r" -ex "bt" -ex "q" --args ctest -C Debug -R "test_rand" --output-on-failure


  # python:
  #   name: Python
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #         - windows-latest
  #       python:
  #         - "3.7"
  #         - "3.8"
  #         - "3.9"
  #         - "3.10"
  #         - "3.11"
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python }}
  #     - name: Install dependencies
  #       run: python -m pip install --upgrade pip setuptools wheel pytest
  #     - name: Install dependencies
  #       if: matrix.os == 'ubuntu-latest'
  #       run: sudo apt-get install -y swig
  #     - name: Install dependencies
  #       if: matrix.os == 'macos-latest'
  #       run: |
  #         brew install bison flex swig
  #         echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
  #         echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
  #     - uses: actions/cache@v2
  #       if: matrix.os == 'windows-latest'
  #       with:
  #         path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
  #         key: ${{ runner.os }}-chocolatey-python-1
  #         restore-keys: |
  #           ${{ runner.os }}-chocolatey-python-
  #           ${{ runner.os }}-chocolatey-
  #     - name: Install dependencies
  #       if: matrix.os == 'windows-latest'
  #       shell: powershell
  #       run: |
  #         choco install winflexbison3 --version 2.5.24.20210105
  #     - name: Select build type
  #       if: matrix.os == 'windows-latest'
  #       shell: powershell
  #       run: |
  #         echo "QX_BUILD_TYPE=Release" >> $GITHUB_ENV
  #         echo "QX_CPU_COMPATIBILITY_MODE=ON" >> $GITHUB_ENV
  #     - name: Select build type
  #       if: matrix.os != 'windows-latest'
  #       run: |
  #         echo "QX_BUILD_TYPE=Debug" >> $GITHUB_ENV
  #         echo "QX_CPU_COMPATIBILITY_MODE=ON" >> $GITHUB_ENV
  #     - name: Build
  #       env:
  #         NPROCS: 5
  #       run: python -m pip install --verbose .
  #     - name: Test
  #       working-directory: tests/qxelarator
  #       run: python -m pytest
