name: Test

on:
  push:
    branches:
      - tweak-test-pipeline-conan
  pull_request:

jobs:
  cpp-linux-x64:
    name: "C++ tests (gcc-clang/Linux/x64)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
        compiler:
          - clang++
          - g++
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cpp-tests
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          shell: bash

  cpp-macos-x64:
    name: "C++ tests (clang/MacOS/x64)"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cpp-tests
        with:
          compiler: clang++
          build_type: ${{ matrix.build_type }}
          shell: bash

  cpp-windows-x64:
    name: "C++ tests (msvc/Windows/x64)"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cpp-tests
        with:
          compiler: msvc
          build_type: ${{ matrix.build_type }}
          shell: bash

  cpp-linux-arm64:
    name: "C++ tests (gcc/Linux/ARM64)"
    runs-on: [self-hosted, ARM64, Linux]
    container: quay.io/pypa/manylinux_2_28_aarch64:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CMake and SWIG
        run: |
          dnf install -y cmake swig
        shell: bash
      - uses: ./.github/actions/cpp-tests
        with:
          compiler: g++
          build_type: Release
          shell: bash

  cpp-macos-arm64:
    name: "C++ tests (clang/macos/ARM64)"
    runs-on: [self-hosted, ARM64, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install gcc
        run: |
          brew install gcc
        shell: bash
      - uses: ./.github/actions/cpp-tests
        with:
          compiler: clang++
          build_type: Release
          shell: bash

  python-linux-x64:
    name: "Python tests (Linux/x64)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SWIG
        run: |
          sudo apt-get install -y swig
        shell: bash
      - uses: ./.github/actions/python-tests
        with:
          shell: bash

  python-macos-x64:
    name: "Python tests (macOS/x64)"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SWIG
        run: |
          brew install swig
        shell: bash
      - uses: ./.github/actions/python-tests
        with:
          shell: bash

  python-windows-x64:
    name: "Python tests (Windows/x64)"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/python-tests
        with:
          shell: powershell

  complete:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: Report status
    needs:
      - cpp-linux-x64
      - cpp-macos-x64
      - cpp-windows-x64
      # - cpp-linux-arm64
      # - cpp-macos-arm64
      - python-linux-x64
      - python-macos-x64
      - python-windows-x64
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
